"""Add notification and dashboard tables for v0.5.4

Revision ID: ec9e73b6d9c3
Revises: 
Create Date: 2025-07-17 18:48:35.461182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9e73b6d9c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('websocket_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('notification_types', sa.JSON(), nullable=False),
    sa.Column('priority_filter', sa.JSON(), nullable=False),
    sa.Column('group_similar', sa.Boolean(), nullable=False),
    sa.Column('max_notifications', sa.Integer(), nullable=False),
    sa.Column('auto_mark_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notification_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_queue_created_at'), 'notification_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_queue_next_retry_at'), 'notification_queue', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_notification_queue_notification_id'), 'notification_queue', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_user_id'), 'notification_queue', ['user_id'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('notification_types', sa.JSON(), nullable=False),
    sa.Column('priority_threshold', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_subscriptions_user_id'), 'notification_subscriptions', ['user_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('title_template', sa.String(length=500), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('default_channel', sa.String(length=100), nullable=True),
    sa.Column('default_expires_in', sa.Integer(), nullable=True),
    sa.Column('action_url_template', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_expires_at'), 'notifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('widget_data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_widget_data_sources_id'), 'widget_data_sources', ['id'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grid_config', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_dashboard_layouts_id'), 'dashboard_layouts', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_user_id'), 'dashboard_layouts', ['user_id'], unique=False)
    op.create_table('dashboard_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('layout_config', sa.JSON(), nullable=False),
    sa.Column('widgets_config', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_templates_id'), 'dashboard_templates', ['id'], unique=False)
    op.create_table('user_dashboard_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto_refresh_interval', sa.Integer(), nullable=False),
    sa.Column('show_grid', sa.Boolean(), nullable=False),
    sa.Column('snap_to_grid', sa.Boolean(), nullable=False),
    sa.Column('compact_mode', sa.Boolean(), nullable=False),
    sa.Column('default_widget_size', sa.JSON(), nullable=False),
    sa.Column('notification_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_dashboard_preferences_id'), 'user_dashboard_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_dashboard_preferences_user_id'), 'user_dashboard_preferences', ['user_id'], unique=True)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('size', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['dashboard_layouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_id'), 'dashboard_widgets', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_layout_id'), 'dashboard_widgets', ['layout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_widgets_layout_id'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_user_dashboard_preferences_user_id'), table_name='user_dashboard_preferences')
    op.drop_index(op.f('ix_user_dashboard_preferences_id'), table_name='user_dashboard_preferences')
    op.drop_table('user_dashboard_preferences')
    op.drop_index(op.f('ix_dashboard_templates_id'), table_name='dashboard_templates')
    op.drop_table('dashboard_templates')
    op.drop_index(op.f('ix_dashboard_layouts_user_id'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_id'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_widget_data_sources_id'), table_name='widget_data_sources')
    op.drop_table('widget_data_sources')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_expires_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_subscriptions_user_id'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    op.drop_index(op.f('ix_notification_queue_user_id'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_notification_id'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_next_retry_at'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_created_at'), table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
